# Generated by Django 3.2.5 on 2023-07-26 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marque', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modele',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(default='', max_length=25)),
                ('marque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modeles', to='marque.marque')),
            ],
        ),
    ]
