# Generated by Django 3.2.5 on 2023-07-26 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marque', '0001_initial'),
        ('modele', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modele',
            name='marque',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marque.marque'),
        ),
    ]
