# Generated by Django 3.2.5 on 2023-07-26 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('imageVoiture', '0001_initial'),
        ('voiture', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagevoiture',
            name='voiture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='voiture.voiture'),
        ),
    ]
