# Generated by Django 3.2.5 on 2023-07-26 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('modele', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voiture',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numeroSerie', models.CharField(max_length=100, unique=True)),
                ('vinNumber', models.CharField(max_length=100, unique=True)),
                ('couleur', models.CharField(max_length=50)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('anneeFabrication', models.PositiveIntegerField()),
                ('puissance', models.FloatField()),
                ('imagePrincipal', models.ImageField(blank=True, default='', null=True, upload_to='voiture_images')),
                ('statutVoiture', models.BooleanField()),
                ('modele', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modele.modele')),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.proprietaire')),
            ],
        ),
    ]
